### ISSUE TITLE
custom_components overwrite 이슈

### ISSUE THREAD

**Issue by JaySeek** [GrecHouse/anniversary-lovelace-card#2]
HACS 통해 설치 시 custom_components를 overwrite를 할지 묻는데, 
OK하면 설치가 진행됨과 동시에 custom_components에 있는 다른 컴포넌트들이 사라져 버립니다.
또한. 이 컴포넌트를 삭제하면 custom_components 폴더 자체가 아예 사라져 버리는 문제가 있습니다.

**Comment by GrecHouse** [comment]
이런, 너무 늦게 이슈를 확인했네요.

HACS Custom repositories 설치시에 "Lovelace" 가 아닌 "Integration" Category 를 선택하신게 아닌가 싶습니다.

정상 설치시 lovelace 카드는 설치경로가 custom_components 가 아니고,
/hacsfiles (실제 경로는 /www/community) 폴더 아래에 js 파일이 생성이 되는 것으로 알고 있습니다.
