### ISSUE TITLE
Home Assistant core-2022.4.0b0 에서 날짜가 제대로 표시되지 않습니다.

### ISSUE THREAD

**Issue by Murianwind** [GrecHouse/anniversary-lovelace-card#3]
![화면 캡처 2022-03-31 094214](https://user-images.githubusercontent.com/6447460/160954100-83320a76-4ad5-439e-b3d4-d01f60212f2a.png)

core-2022.4.0b0 에서 날짜 표시가 제대로 되지 않습니다.

**Comment by GrecHouse** [comment]
센서 속성값을 처리하는 프로퍼티 변수명이 변경이 되어 발생한 문제입니다.
한동안 업데이트에 신경을 안 썼더니 warning 이 뜨고 있는지도 몰랐네요.
기념일 센서를 업데이트 했습니다. 신고 감사합니다.
